"""Installing the pipeline's systemd units for the user manager.

A unit carries an absolute `WorkingDirectory`, so it is correct for exactly one
checkout at one path. Rendering them into the planning repo at init time baked
in whoever ran init: everyone who cloned that repo afterwards got units aimed at
someone else's home directory, and `systemctl --user enable` took them without
complaint, because a unit naming a directory that is not there is still a valid
unit. So they are rendered here instead - on the machine doing the installing,
against the installation being installed for - and nothing machine-specific is
committed.

**Every unit is named for its installation.** One machine may run several, and
the user manager has one namespace: units named for the framework alone would
have a second install replace the first's, both carrying this module's marker so
nothing would refuse it, and the first workspace would simply stop being ticked
with nothing to see. The installation's directory name goes in the unit name,
which also makes `systemctl --user list-timers` answer "whose timer is that".

Installing is idempotent. A unit already there with the content it should have is
left alone, down to its modification time, and the manager is not asked to reload
for a change that did not happen - so the command is safe in a setup script that
runs on every boot.

`systemctl` goes through an injectable runner, as everything external does.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from agent_build_kit import config, runtimes
from agent_build_kit.init.scaffold import render_systemd
from agent_build_kit.model import Frozen
from agent_build_kit.settings import settings

if TYPE_CHECKING:
    from agent_build_kit.installation import Installation

Run = Callable[..., subprocess.CompletedProcess]

# Written into every rendered unit; a file without it belongs to someone else.
MARKER = "# generated by agent-build-kit"

# What this framework installs, before the installation's name is worked in.
BASE_UNITS = (
    "tick.service",
    "tick.timer",
    "track-health.service",
    "track-health.timer",
    "track-improve.service",
    "track-improve.timer",
    "track-recommend.service",
    "track-recommend.timer",
)

# What systemd accepts in a unit name. A checkout directory may be called
# anything at all - `My%20Project` is a valid one - so the name is made safe
# rather than assumed to be.
SAFE_CHARACTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."

_UNSAFE = re.compile(r"[^A-Za-z0-9_.]+")
_WORKING_DIRECTORY = "WorkingDirectory="
_PATH_LINE = re.compile(r'^Environment="PATH=(.*)"$', re.M)

# The PATH every unit starts with (see the templates): `%h` is the user's home.
# A tool on one of these needs nothing added.
BASE_PATH = (
    "%h/.local/bin",
    "%h/.volta/bin",
    "/usr/local/sbin",
    "/usr/local/bin",
    "/usr/sbin",
    "/usr/bin",
    "/sbin",
    "/bin",
)


class UnitChange(Frozen):
    """What an install or a remove did, by unit path.

    Separate lists rather than a pair, because "already correct" and "written"
    are different answers and a caller that cannot tell them apart reports
    eight writes every time it runs. `refused` is a file somebody else wrote;
    `taken` is one this framework wrote for a *different, live* installation
    that happens to share this one's directory name.
    """

    written: tuple[Path, ...] = ()
    unchanged: tuple[Path, ...] = ()
    refused: tuple[Path, ...] = ()
    taken: tuple[Path, ...] = ()
    removed: tuple[Path, ...] = ()

    @property
    def touched(self) -> bool:
        """Whether the manager needs to be told anything."""
        return bool(self.written or self.removed)


def user_unit_dir() -> Path:
    """Where the user manager reads units from, XDG first."""
    base = settings.config_home or Path.home() / ".config"
    return Path(base).expanduser() / "systemd" / "user"


def slug(root: Path) -> str:
    """The installation's name as a unit name may spell it."""
    cleaned = _UNSAFE.sub("-", root.expanduser().resolve().name).strip("-")
    return cleaned or "workspace"


def unit_names(root: Path) -> list[str]:
    """The unit file names this installation owns."""
    return [f"abk-{slug(root)}-{base}" for base in BASE_UNITS]


def needed_tools(inst: Installation) -> list[str]:
    """The commands a tick runs that are not the framework's own: `uv` starts it,
    the agent runtime does the work, and each repo's forge client talks to its
    host. A unit has no login environment, so each has to be findable from the
    PATH the unit is given."""
    name = config.runtime_name(inst.config)
    command = config.runtime_entry(inst.config).command or list(runtimes.get(name).agent_command)
    tools = ["uv", *command[:1]]
    for repo in inst.repos:
        if client := inst.forge_of(repo)[0].client:
            tools.append(client)
    return list(dict.fromkeys(tool for tool in tools if tool))


def _expand(path: str) -> str:
    """A unit's PATH entry as the manager reads it: `%h` is home, `%%` a percent."""
    return path.replace("%h", str(Path.home())).replace("%%", "%")


def tool_dirs(
    inst: Installation, *, which: Callable[[str], str | None] = shutil.which
) -> tuple[str, ...]:
    """The directories to add to a unit's PATH so it finds what a tick runs.

    Asked of the machine doing the installing, which is the one whose login
    environment knows where `az` lives (on WSL, under the Windows install). A
    tool already on the unit's base PATH adds nothing, and one nothing can find
    adds nothing either: `abk doctor` is what reports that, not an install.
    """
    base = {_expand(entry) for entry in BASE_PATH}
    found: list[str] = []
    for tool in needed_tools(inst):
        location = which(tool)
        if location is None:
            continue
        folder = str(Path(location).parent)
        if folder not in base and folder not in found:
            found.append(folder)
    return tuple(found)


def render(root: Path, tool_dirs: Sequence[str] = ()) -> dict[str, str]:
    """Unit name -> text, each named for its installation and stamped so a
    later install knows it wrote it.

    `tool_dirs` go at the *end* of the unit's PATH, so a directory like the
    Windows CLI's can supply `az` without being able to shadow a system tool.
    A `%` in a directory is doubled: the manager reads `%x` as a specifier.
    """
    root = root.expanduser().resolve()
    rendered = render_systemd(
        root, tool_path="".join(":" + folder.replace("%", "%%") for folder in tool_dirs)
    )
    return {
        f"abk-{slug(root)}-{base}": f"{MARKER}\n{rendered[f'abk-{base}']}" for base in BASE_UNITS
    }


def _is_ours(path: Path) -> bool:
    """Whether this framework wrote the file."""
    try:
        return MARKER in path.read_text()
    except OSError:
        return False


def _working_directory(service: Path) -> Path | None:
    """Where a service unit says it runs."""
    try:
        text = service.read_text()
    except OSError:
        return None
    for line in text.splitlines():
        if line.startswith(_WORKING_DIRECTORY):
            return Path(line[len(_WORKING_DIRECTORY) :].strip())
    return None


def owner_of(unit: Path) -> Path | None:
    """The installation a unit file serves: where its service runs. A timer
    names no directory of its own, so whose it is is whose service it fires."""
    return _working_directory(unit.with_suffix(".service"))


def installed_units(root: Path, dest: Path | None = None) -> list[Path]:
    """Every unit in `dest` that belongs to this installation — current or not.

    Ownership is where a unit *points*, never what its name starts with.
    Installation `meta`'s units begin `abk-meta-`, and so do installation
    `meta-agent`'s; matching by prefix would call one's units the other's and
    delete them. A service belongs here when this framework wrote it and its
    `WorkingDirectory` is this root, and its timer goes with it.
    """
    dest = dest or user_unit_dir()
    if not dest.is_dir():
        return []
    root = root.expanduser().resolve()
    found: list[Path] = []
    for service in sorted(dest.glob("abk-*.service")):
        where = _working_directory(service)
        if not _is_ours(service) or where is None or where.resolve() != root:
            continue
        found.append(service)
        timer = service.with_suffix(".timer")
        if timer.is_file() and _is_ours(timer):
            found.append(timer)
    return found


def outdated_units(root: Path, dest: Path | None = None) -> list[Path]:
    """This installation's units that the current version no longer installs.

    What an earlier version named differently (before units carried their
    installation's name, `abk-tick.service` sat beside the new one running the
    same tick twice), or a later one dropped from the set. Reinstalling is how
    a machine is brought up to date, so it has to clean up after both.
    """
    current = set(unit_names(root))
    return [path for path in installed_units(root, dest) if path.name not in current]


def dangling_units(dest: Path | None = None) -> list[Path]:
    """Service units this framework wrote that point at a directory that is gone.

    A unit naming a directory that is not there is still a valid unit, and
    `systemctl --user enable` accepts it without complaint - so the pipeline
    fails every five minutes with nothing to see. Found for any installation,
    not just this one: the point is that nobody is left to remove them.
    """
    dest = dest or user_unit_dir()
    if not dest.is_dir():
        return []
    found = []
    for service in sorted(dest.glob("abk-*.service")):
        where = _working_directory(service)
        if _is_ours(service) and where is not None and not where.exists():
            found.append(service)
    return found


class TimerReport(Frozen):
    """Where this installation's units stand, without touching anything."""

    installed: bool
    missing: tuple[str, ...] = ()
    drifted: tuple[Path, ...] = ()
    outdated: tuple[Path, ...] = ()


def report(root: Path, *, dest: Path | None = None, tool_dirs: Sequence[str] = ()) -> TimerReport:
    """Whether the units on this machine are the ones install would write now.

    `drifted` is a current unit whose content differs from the template — the
    same test `install` uses to decide a file needs rewriting, so a report that
    says everything is fine means a reinstall would change nothing.
    """
    dest = dest or user_unit_dir()
    wanted = render(root, tool_dirs)
    missing = tuple(name for name in wanted if not (dest / name).is_file())
    drifted = tuple(
        dest / name
        for name, text in wanted.items()
        if (dest / name).is_file() and _is_ours(dest / name) and (dest / name).read_text() != text
    )
    present = len(wanted) - len(missing)
    return TimerReport(
        installed=present > 0,
        missing=missing,
        drifted=drifted,
        outdated=tuple(outdated_units(root, dest)),
    )


def _stop_and_delete(paths: list[Path], run: Run) -> None:
    """Stop and disable the timers among `paths`, then delete the files.

    In that order: a unit file deleted from under a running timer leaves the
    manager holding a job it can no longer describe.
    """
    for path in paths:
        if path.name.endswith(".timer"):
            run(["systemctl", "--user", "disable", "--now", path.name], check=False)
    for path in paths:
        path.unlink(missing_ok=True)


def install(
    root: Path,
    *,
    dest: Path | None = None,
    run: Run | None = None,
    enable: bool = True,
    dry_run: bool = False,
    tool_dirs: Sequence[str] = (),
) -> UnitChange:
    """Render this installation's units into `dest`, enable them, and report
    what changed.

    Enabled by default because that is what installing a timer is for. Written
    but not enabled is the failure that looks most like success: `abk status`
    answers perfectly while no tick has happened in a week. `enable=False` is
    for a caller that wants the files and will schedule them itself.

    A unit already there without the marker is refused rather than overwritten.
    One this framework wrote for a *different installation that still exists* is
    taken over by nobody: two planning repos both called `planning` produce the
    same unit names, and overwriting would stop the first silently. One whose
    directory is gone, or that points here, is replaced only when its content
    has moved on, which is what makes reinstalling the repair for a template
    that changed or a planning repo that moved, while costing nothing when
    neither has happened.

    Units of this installation that the current version no longer installs are
    stopped and removed, so reinstalling also heals what an earlier version
    left behind.
    """
    run = run or subprocess.run
    dest = dest or user_unit_dir()
    here = root.expanduser().resolve()

    written: list[Path] = []
    unchanged: list[Path] = []
    refused: list[Path] = []
    taken: list[Path] = []
    for name, text in render(root, tool_dirs).items():
        target = dest / name
        if target.exists():
            current = target.read_text()
            if MARKER not in current:
                refused.append(target)
                continue
            # A timer names no directory of its own: whose it is is whose
            # service it fires.
            owner = owner_of(target)
            if owner is not None and owner.resolve() != here and owner.exists():
                taken.append(target)
                continue
            if current == text:
                unchanged.append(target)
                continue
        written.append(target)
        if dry_run:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)

    outdated = outdated_units(root, dest)
    change = UnitChange(
        written=tuple(written),
        unchanged=tuple(unchanged),
        refused=tuple(refused),
        taken=tuple(taken),
        removed=tuple(outdated),
    )
    if dry_run:
        return change

    _stop_and_delete(outdated, run)
    if change.touched:
        run(["systemctl", "--user", "daemon-reload"], check=False)
    if enable:
        # Timers only: enabling a .service would run it at boot, outside the
        # schedule that is the whole point of the timer beside it. `enable
        # --now` is idempotent, so it runs whether or not anything was written.
        for name in unit_names(root):
            if name.endswith(".timer") and (dest / name).is_file() and (dest / name) not in taken:
                run(["systemctl", "--user", "enable", "--now", name], check=False)
    return change


def remove(
    root: Path,
    *,
    dest: Path | None = None,
    run: Run | None = None,
    dry_run: bool = False,
) -> UnitChange:
    """Take this installation's units off this machine, current and outdated.

    The timers are stopped and disabled before the files go: a unit file deleted
    from under a running timer leaves the manager holding a job it can no longer
    describe. Only files this framework wrote are removed, and only those that
    point at this installation — another workspace's units are none of our
    business.
    """
    run = run or subprocess.run
    dest = dest or user_unit_dir()

    ours = installed_units(root, dest)
    if not ours or dry_run:
        return UnitChange(removed=tuple(ours))

    _stop_and_delete(ours, run)
    run(["systemctl", "--user", "daemon-reload"], check=False)
    return UnitChange(removed=tuple(ours))


def installed_root(dest: Path | None = None, root: Path | None = None) -> Path | None:
    """The installation the units on this machine serve, or None if there are none.

    With `root`, answers for that installation's own units; without one, for the
    first set found, which is the answer when only one is installed.
    """
    dest = dest or user_unit_dir()
    if not dest.is_dir():
        return None
    candidates = (
        [dest / f"abk-{slug(root)}-tick.service"]
        if root is not None
        else sorted(dest.glob("abk-*-tick.service"))
    )
    for unit in candidates:
        if unit.is_file():
            where = _working_directory(unit)
            if where is not None:
                return where
    return None


def service_path(root: Path, dest: Path | None = None) -> list[str] | None:
    """The PATH the installed tick service will run with, or None when there is
    no such unit. Read from the unit, not worked out again: what matters is what
    the manager will do, not what a reinstall would write."""
    unit = (dest or user_unit_dir()) / f"abk-{slug(root)}-tick.service"
    try:
        match = _PATH_LINE.search(unit.read_text())
    except OSError:
        return None
    return [_expand(entry) for entry in match.group(1).split(":")] if match else None


def unreachable(
    inst: Installation,
    dest: Path | None = None,
    *,
    which: Callable[[str], str | None] = shutil.which,
) -> list[tuple[str, bool]]:
    """What a tick needs that its installed service cannot find, each with
    whether the installing user's own shell can (so a reinstall would fix it).

    This is the check a person's terminal passes by accident: `az` is on their
    PATH and not on the unit's, every command they run by hand works, and the
    scheduled poll fails on every tick. A tool is reachable when the directory
    the shell finds it in is on the unit's PATH — the same test `tool_dirs`
    installs by, so what an install adds is exactly what stops being reported.
    A tool the shell cannot find is reported too, as not fixable by reinstalling.
    Nothing here searches the real filesystem beyond `which`, so it answers the
    same way on every machine.
    """
    path = service_path(inst.root, dest)
    if path is None:
        return []
    missing: list[tuple[str, bool]] = []
    for tool in needed_tools(inst):
        found = which(tool)
        if found is not None and str(Path(found).parent) in path:
            continue
        missing.append((tool, found is not None))
    return missing
