"""Installing the pipeline's systemd units for the user manager.

A unit carries an absolute `WorkingDirectory`, so it is correct for exactly one
checkout at one path. Rendering them into the planning repo at init time baked
in whoever ran init: everyone who cloned that repo afterwards got units aimed at
someone else's home directory, and `systemctl --user enable` took them without
complaint because a unit naming a directory that is not there is still a valid
unit. So they are rendered here instead - on the machine doing the installing,
against the installation being installed for - and nothing machine-specific is
committed.

`systemctl` goes through an injectable runner, as everything external does.
"""

from __future__ import annotations

import subprocess
from collections.abc import Callable
from pathlib import Path

from agent_build_kit.init.scaffold import render_systemd
from agent_build_kit.settings import settings

Run = Callable[..., subprocess.CompletedProcess]

# Written into every rendered unit; a file without it belongs to someone else.
MARKER = "# generated by agent-build-kit"

UNITS = (
    "abk-tick.service",
    "abk-tick.timer",
    "abk-track-health.service",
    "abk-track-health.timer",
    "abk-track-improve.service",
    "abk-track-improve.timer",
    "abk-track-recommend.service",
    "abk-track-recommend.timer",
)

_WORKING_DIRECTORY = "WorkingDirectory="


def user_unit_dir() -> Path:
    """Where the user manager reads units from, XDG first."""
    base = settings.config_home or Path.home() / ".config"
    return Path(base).expanduser() / "systemd" / "user"


def render(root: Path) -> dict[str, str]:
    """Unit name -> text, each stamped so a later install knows it wrote it."""
    return {name: f"{MARKER}\n{text}" for name, text in render_systemd(root).items()}


def install(
    root: Path,
    *,
    dest: Path | None = None,
    run: Run | None = None,
    enable: bool = False,
    dry_run: bool = False,
) -> tuple[list[Path], list[Path]]:
    """Render the units for `root` into `dest`; return what was written and refused.

    A unit already there without the marker is refused rather than overwritten.
    One this framework wrote is replaced, which is what makes reinstalling the
    repair for a planning repo that moved.
    """
    run = run or subprocess.run
    dest = dest or user_unit_dir()
    root = root.expanduser().resolve()

    written: list[Path] = []
    refused: list[Path] = []
    for name, text in render(root).items():
        target = dest / name
        if target.exists() and MARKER not in target.read_text():
            refused.append(target)
            continue
        written.append(target)
        if dry_run:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)

    if dry_run or not written:
        return written, refused

    run(["systemctl", "--user", "daemon-reload"], check=False)
    if enable:
        # Timers only: enabling a .service would run it at boot, outside the
        # schedule that is the whole point of the timer beside it.
        for name in UNITS:
            if name.endswith(".timer"):
                run(["systemctl", "--user", "enable", "--now", name], check=False)
    return written, refused


def installed_root(dest: Path | None = None) -> Path | None:
    """The installation the units on this machine serve, or None if there are none."""
    dest = dest or user_unit_dir()
    unit = dest / "abk-tick.service"
    if not unit.is_file():
        return None
    for line in unit.read_text().splitlines():
        if line.startswith(_WORKING_DIRECTORY):
            return Path(line[len(_WORKING_DIRECTORY) :].strip())
    return None
