"""Installing the pipeline's systemd units for the user manager.

A unit carries an absolute `WorkingDirectory`, so it is correct for exactly one
checkout at one path. Rendering them into the planning repo at init time baked
in whoever ran init: everyone who cloned that repo afterwards got units aimed at
someone else's home directory, and `systemctl --user enable` took them without
complaint, because a unit naming a directory that is not there is still a valid
unit. So they are rendered here instead - on the machine doing the installing,
against the installation being installed for - and nothing machine-specific is
committed.

**Every unit is named for its installation.** One machine may run several, and
the user manager has one namespace: units named for the framework alone would
have a second install replace the first's, both carrying this module's marker so
nothing would refuse it, and the first workspace would simply stop being ticked
with nothing to see. The installation's directory name goes in the unit name,
which also makes `systemctl --user list-timers` answer "whose timer is that".

Installing is idempotent. A unit already there with the content it should have is
left alone, down to its modification time, and the manager is not asked to reload
for a change that did not happen - so the command is safe in a setup script that
runs on every boot.

`systemctl` goes through an injectable runner, as everything external does.
"""

from __future__ import annotations

import re
import subprocess
from collections.abc import Callable
from pathlib import Path

from agent_build_kit.init.scaffold import render_systemd
from agent_build_kit.model import Frozen
from agent_build_kit.settings import settings

Run = Callable[..., subprocess.CompletedProcess]

# Written into every rendered unit; a file without it belongs to someone else.
MARKER = "# generated by agent-build-kit"

# What this framework installs, before the installation's name is worked in.
BASE_UNITS = (
    "tick.service",
    "tick.timer",
    "track-health.service",
    "track-health.timer",
    "track-improve.service",
    "track-improve.timer",
    "track-recommend.service",
    "track-recommend.timer",
)

# What systemd accepts in a unit name. A checkout directory may be called
# anything at all - `AI%20Accelerators` is a real one - so the name is made safe
# rather than assumed to be.
SAFE_CHARACTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_."

_UNSAFE = re.compile(r"[^A-Za-z0-9_.]+")
_WORKING_DIRECTORY = "WorkingDirectory="


class UnitChange(Frozen):
    """What an install or a remove did, by unit path.

    Four lists rather than a pair, because "already correct" and "written" are
    different answers and a caller that cannot tell them apart reports eight
    writes every time it runs.
    """

    written: tuple[Path, ...] = ()
    unchanged: tuple[Path, ...] = ()
    refused: tuple[Path, ...] = ()
    removed: tuple[Path, ...] = ()

    @property
    def touched(self) -> bool:
        """Whether the manager needs to be told anything."""
        return bool(self.written or self.removed)


def user_unit_dir() -> Path:
    """Where the user manager reads units from, XDG first."""
    base = settings.config_home or Path.home() / ".config"
    return Path(base).expanduser() / "systemd" / "user"


def slug(root: Path) -> str:
    """The installation's name as a unit name may spell it."""
    cleaned = _UNSAFE.sub("-", root.expanduser().resolve().name).strip("-")
    return cleaned or "workspace"


def unit_names(root: Path) -> list[str]:
    """The unit file names this installation owns."""
    return [f"abk-{slug(root)}-{base}" for base in BASE_UNITS]


def render(root: Path) -> dict[str, str]:
    """Unit name -> text, each named for its installation and stamped so a
    later install knows it wrote it."""
    root = root.expanduser().resolve()
    rendered = render_systemd(root)
    return {
        f"abk-{slug(root)}-{base}": f"{MARKER}\n{rendered[f'abk-{base}']}" for base in BASE_UNITS
    }


def install(
    root: Path,
    *,
    dest: Path | None = None,
    run: Run | None = None,
    enable: bool = False,
    dry_run: bool = False,
) -> UnitChange:
    """Render this installation's units into `dest`, and report what changed.

    A unit already there without the marker is refused rather than overwritten.
    One this framework wrote is replaced only when its content has moved on,
    which is what makes reinstalling the repair for a template that changed
    while costing nothing when it has not.
    """
    run = run or subprocess.run
    dest = dest or user_unit_dir()

    written: list[Path] = []
    unchanged: list[Path] = []
    refused: list[Path] = []
    for name, text in render(root).items():
        target = dest / name
        if target.exists():
            current = target.read_text()
            if MARKER not in current:
                refused.append(target)
                continue
            if current == text:
                unchanged.append(target)
                continue
        written.append(target)
        if dry_run:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)

    change = UnitChange(written=tuple(written), unchanged=tuple(unchanged), refused=tuple(refused))
    if dry_run:
        return change

    if change.touched:
        run(["systemctl", "--user", "daemon-reload"], check=False)
    if enable:
        # Timers only: enabling a .service would run it at boot, outside the
        # schedule that is the whole point of the timer beside it.
        for name in unit_names(root):
            if name.endswith(".timer"):
                run(["systemctl", "--user", "enable", "--now", name], check=False)
    return change


def remove(
    root: Path,
    *,
    dest: Path | None = None,
    run: Run | None = None,
    dry_run: bool = False,
) -> UnitChange:
    """Take this installation's units off this machine.

    The timers are stopped and disabled before the files go: a unit file deleted
    from under a running timer leaves the manager holding a job it can no longer
    describe. Only files this framework wrote are removed, and only this
    installation's — another workspace's units are none of our business.
    """
    run = run or subprocess.run
    dest = dest or user_unit_dir()

    ours = [
        dest / name
        for name in unit_names(root)
        if (dest / name).is_file() and MARKER in (dest / name).read_text()
    ]
    if not ours or dry_run:
        return UnitChange(removed=tuple(ours))

    for path in ours:
        if path.name.endswith(".timer"):
            run(["systemctl", "--user", "disable", "--now", path.name], check=False)
    for path in ours:
        path.unlink()
    run(["systemctl", "--user", "daemon-reload"], check=False)
    return UnitChange(removed=tuple(ours))


def installed_root(dest: Path | None = None, root: Path | None = None) -> Path | None:
    """The installation the units on this machine serve, or None if there are none.

    With `root`, answers for that installation's own units; without one, for the
    first set found, which is the answer when only one is installed.
    """
    dest = dest or user_unit_dir()
    if not dest.is_dir():
        return None
    candidates = (
        [dest / f"abk-{slug(root)}-tick.service"]
        if root is not None
        else sorted(dest.glob("abk-*-tick.service"))
    )
    for unit in candidates:
        if not unit.is_file():
            continue
        for line in unit.read_text().splitlines():
            if line.startswith(_WORKING_DIRECTORY):
                return Path(line[len(_WORKING_DIRECTORY) :].strip())
    return None
